import argparse
import yaml
import os.path
import common

def html_header():
    returned = ""
    returned += "<html>\n"
    returned += "<body>\n"
    returned +=  "<table>\n"
    return returned

def link_to_osm_object(url):
    return '<a href="' + url + '" target="_new">OSM element with broken tag that should be fixed</a>'

def article_name_from_wikipedia_string(string):
    return string[string.find(":")+1:]

def language_code_from_wikipedia_string(string):
    return string[0:string.find(":")]

def format_wikipedia_link(string):
    if string == None:
        return "?"
    language_code = language_code_from_wikipedia_string(string)
    language_code = common.escape_from_internal_python_string_to_html_ascii(language_code)
    article_name = article_name_from_wikipedia_string(string)
    article_name = common.escape_from_internal_python_string_to_html_ascii(article_name)
    return '<a href="https://' + language_code + '.wikipedia.org/wiki/' + article_name + '" target="_new">' + language_code+":"+article_name + '</a>'

def table_row(text):
    returned = ""
    returned += "<tr>\n"
    returned += "<td>\n"
    returned += text
    returned += "</td>\n"
    returned += "</tr>\n"
    return returned

def parsed_args():
    parser = argparse.ArgumentParser(description='Production of webpage about validation of wikipedia tag in osm data.')
    parser.add_argument('-file', '-f', dest='file', type=str, help='name of yaml file produced by validator')
    args = parser.parse_args()
    if not (args.file):
        parser.error('Provide yaml file generated by wikipedia validator')
    return args

def displayed_types():
    return [
        'wikipedia tag in outdated form and wikidata - mismatch',
        'wikipedia tag links to 404',
        'link to unlinkable article',
        'wikipedia wikidata mismatch',
        'should use wikipedia:subject',
        'wikipedia from wikipedia tag in outdated form - mismatch',
        'wikipedia from wikidata tag',
        'wikipedia from wikipedia tag in outdated form',
        'wikipedia tag unexpected language',
        'wikipedia wikidata mismatch - follow redirect',
    ]

def get_errors(args):
    filepath = common.get_file_storage_location()+"/"+args.file
    if not os.path.isfile(filepath):
        print(filepath + " is not a file, provide an existing file")
        return []
    return common.load_data(filepath)

def error_description(e):
    returned = ""
    returned += table_row(common.htmlify(e['error_message']))
    returned += table_row(link_to_osm_object(e['osm_object_url']))
    current = format_wikipedia_link(e['current_wikipedia_target'])
    to = format_wikipedia_link(e['desired_wikipedia_target'])
    if to == current:
        to = "?"
    returned += table_row( current + " -> " + to)
    if to != "?":
        article_name = article_name_from_wikipedia_string(e['desired_wikipedia_target'])
        returned += table_row( common.escape_from_internal_python_string_to_html_ascii(article_name))
    returned += table_row( '-------' )
    return returned

def main():
    args = parsed_args()
    print(html_header())
    reported_errors = get_errors(args)
    for error_type_id in displayed_types():
        error_count = 0
        for e in reported_errors:
            if e['error_id'] == error_type_id:
                error_count += 1
                print(error_description(e))
        if error_count != 0:
            print(table_row( 'overpass query usable in JOSM that will load all objects with this error type:' ))
            query = common.get_query_for_loading_errors_by_category(filename = args.file, printed_error_ids = [error_type_id], format = "josm")
            print(table_row(common.escape_from_internal_python_string_to_html_ascii(query)))
            print(table_row( '==========' ))

    print("</table>")
    print("</body>")
    print("</html>")

if __name__ == "__main__":
    main()
